"""empty message

Revision ID: 4cc44e4bdaf8
Revises: 5d2c977d885c
Create Date: 2021-07-05 21:37:41.835160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc44e4bdaf8'
down_revision = '5d2c977d885c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_space', sa.Column('documentation', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_space', 'documentation')
    # ### end Alembic commands ###
