"""empty message

Revision ID: 5d2c977d885c
Revises: 4d2502d2587c
Create Date: 2021-07-05 21:37:10.961888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d2c977d885c'
down_revision = '4d2502d2587c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_space', 'documentation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_space', sa.Column('documentation', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
