"""empty message

Revision ID: cf726c030f24
Revises: f13972a8caf0
Create Date: 2021-07-05 22:21:46.477796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf726c030f24'
down_revision = 'f13972a8caf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_space', sa.Column('documentation', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_space', 'documentation')
    # ### end Alembic commands ###
