"""empty message

Revision ID: f13972a8caf0
Revises: 4cc44e4bdaf8
Create Date: 2021-07-05 22:21:30.391770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13972a8caf0'
down_revision = '4cc44e4bdaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_space', 'documentation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_space', sa.Column('documentation', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
